var R=require("../../chunks/ssr/[turbopack]_runtime.js")("server/app/termos/page.js")
R.c("server/chunks/ssr/[root-of-the-server]__1zpp3rt._.js")
R.c("server/chunks/ssr/0ema_next_dist_1phlmug._.js")
R.c("server/chunks/ssr/[root-of-the-server]__1ggfbcf._.js")
R.c("server/chunks/ssr/[root-of-the-server]__0h_bv94._.js")
R.c("server/chunks/ssr/app_layout_tsx_2144vk_._.js")
R.c("server/chunks/ssr/0ema_next_dist_client_components_0s_oac4._.js")
R.c("server/chunks/ssr/0ema_next_dist_client_components_builtin_forbidden_1_yc7qh.js")
R.c("server/chunks/ssr/0ema_next_dist_client_components_builtin_unauthorized_1auix7k.js")
R.c("server/chunks/ssr/0ema_next_dist_client_components_builtin_global-error_13agc-i.js")
R.c("server/chunks/ssr/_next-internal_server_app_termos_page_actions_0kt7p08.js")
R.m(21269)
module.exports=R.m(21269).exports
